[img]
out = "./img/functora-card-"
dpi = 96
width = 2100
height = 1200
padX = 85
padY = 20

[font]
head = "./fonts/larabiefont.ttf"
icon = "./fonts/devicons.ttf"
note = "./fonts/rondo.ttf"

[[extra]]
width = 2400
height = 1200
vertical = true

[[group]]
[[group.item]]
kind = "Head"
data = "Functora"
size = 150
padX = 595
[[group.item]]
data = "0xe602"
kind = "Icon"
size = 260
padX = 120
padY = -10
[[group.item]]
data = "https://functora.github.io"
kind = "Qr"
size = 594
padY = 40
[[group.item]]
data = "https://functora.github.io"
kind = "Note"
size = 30
padY = 0

[[group]]
[[group.item]]
kind = "Head"
data = ""
size = 150
[[group.item]]
data = "0xe6a8"
kind = "Icon"
size = 300
padX = 138
padY = -30
[[group.item]]
data = "https://functora.github.io/apps/cryptonote"
kind = "Qr"
size = 594
[[group.item]]
data = "https://functora.github.io/apps/"
kind = "Note"
size = 30
padY = 16
[[group.item]]
data = "cryptonote"
kind = "Note"
size = 30
padY = 0

[[group]]
[[group.item]]
kind = "Head"
data = ""
size = 150
[[group.item]]
data = "0xe677"
kind = "Icon"
size = 300
padX = 100
padY = -30
[[group.item]]
data = "https://functora.github.io/apps/currency-converter"
kind = "Qr"
size = 594
[[group.item]]
data = "https://functora.github.io/apps/"
kind = "Note"
size = 30
padY = 8
[[group.item]]
data = "currency-converter"
kind = "Note"
size = 30
padY = 0
